## READ THIS FIRST
#  idp_cert can be omitted if you have idp_cert_fingerprint and idp_cert_fingerprint_algorithm

identity_providers:
  onelogin:
    #Mandatory Settings
    idp_homepage:
    idp_entity_id:
    idp_sso_target_url:
    issuer:
    assertion_consumer_service_url:
    name_identifier_format:
    assertion_consumer_service_binding:
    idp_cert_fingerprint_algorithm:
    idp_cert_fingerprint:
    #Optional Settings, set these up if using SLO as well
#    idp_slo_target_url: 
#    single_logout_service_binding:
#    idp_cert:

  okta:
    idp_homepage:
    idp_entity_id:
    idp_sso_target_url:
    issuer:
    assertion_consumer_service_url:
    name_identifier_format:
    assertion_consumer_service_binding:
    idp_cert_fingerprint_algorithm:
    idp_cert_fingerprint:
#    idp_slo_target_url:
#    single_logout_service_binding:
#    idp_cert:

    #Optional security settings
    security:
      logout_requests_signed:
      authn_requests_signed:
      want_assertions_signed:
      metadata_signed:
      signature_method:
      digest_method:
    #certificate for signing SLO request
    certificate:
    #private key of certificate above
    private_key:
